package controller

import (
	"context"
	"fmt"
	"github.com/Nicole8493/GoLingo/usecase"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/monitor"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/gofiber/swagger"
	"github.com/mymmrac/telego"
	th "github.com/mymmrac/telego/telegohandler"
	"github.com/swaggo/swag/testdata/enums/api"

	// docs are generated by Swag CLI, you have to import them.
	//_ "payapi/docs"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

type Controller struct {
	fiber   *fiber.App // router to add handlers
	config  domain.Config
	usecase usecase.Usecase
	db      *gorm.DB
}

func New(
	config domain.Config,
	usecase usecase.Usecase,
	db *gorm.DB,
) (*Controller, error) {
	app := fiber.New()
	ctx := context.Background()

	controller := &Controller{
		config:  config,
		usecase: usecase,
		db:      db,
	}

	app.Use(logger.New(logger.ConfigDefault))
	app.Get("/swagger/*", swagger.HandlerDefault)
	app.Get("/swagger/*", swagger.New(swagger.Config{ // custom
		URL:         "http://localhost:8081/doc.json",
		DeepLinking: false,
		// Expand ("list") or Collapse ("none") tag groups by default
		DocExpansion: "none",
	}))

	app.Get("/", func(c *fiber.Ctx) error { // на пустую строку запроса будет ответ Hello 👋!
		return c.SendString("Hello 👋!")
	})

	// Initialize default config
	app.Use(recover.New()) // добавляем мидлварю отлова паники

	app.Use(requestid.New()) // добавляем мидлварю (к запросу добавляется уник айди для поиска)

	apiGroup := app.Group("/api", controller.authMiddleware)
	{
		apiGroup.Post("/article", controller.handlerCreateArticle)
		apiGroup.Post("/translations/:id", controller.handlerUpdateTranslations)
		apiGroup.Get("/article/full/:id", controller.handlerGetFullArticle)
		apiGroup.Get("/article/:id", controller.handlerGetArticle)
		apiGroup.Delete("/translations/:id", controller.handlerDeleteTranslations)
		apiGroup.Delete("/article/:id", controller.handlerDeleteArticle)
	}

	controller.fiber = app
	return controller, nil
}

func (w *Controller) Run(ctx context.Context) error {
	go func() {
		<-ctx.Done()
		err := w.fiber.Shutdown()
		zap.L().Error("can't graceful shutdown fiber", zap.Error(err))
	}()

	err := w.fiber.Listen(w.config.WebAddr)
	if err != nil {
		return err
	}
	return nil
}
