package controller

import (
	"context"
	"github.com/Nicole8493/GoLingo/config"
	"github.com/Nicole8493/GoLingo/usecase"
	jwtware "github.com/gofiber/contrib/jwt"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/gofiber/swagger"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/Nicole8493/GoLingo/docs"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

type Controller struct {
	fiber   *fiber.App // router to add handlers
	config  config.Config
	usecase usecase.Usecase
	db      *gorm.DB
	key     string
}

func New(
	config config.Config,
	usecase usecase.Usecase,
	db *gorm.DB,
) (*Controller, error) {
	app := fiber.New()

	controller := &Controller{
		config:  config,
		usecase: usecase,
		db:      db,
		key:     config.PrivateKey,
		fiber:   app,
	}

	app.Use(logger.New(logger.ConfigDefault))
	app.Get("/swagger/*", swagger.HandlerDefault)
	app.Get("/swagger/*", swagger.New(swagger.Config{ // custom
		URL:         "http://localhost:8081/doc.json",
		DeepLinking: false,
		// Expand ("list") or Collapse ("none") tag groups by default
		DocExpansion: "none",
	}))

	app.Get("/", func(c *fiber.Ctx) error { // на пустую строку запроса будет ответ Hello 👋!
		return c.SendString("Hello 👋!")
	})

	// Initialize default config
	app.Use(recover.New()) // добавляем мидлварю отлова паники

	app.Use(requestid.New()) // добавляем мидлварю (к запросу добавляется уник айди для поиска)

	apiGroup := app.Group("/api")
	{
		apiGroup.Get("/article/full/:id", controller.handlerGetFullArticle)
		apiGroup.Get("/article/:id", controller.handlerGetArticle)
		apiGroup.Get("/articles/group/:id", controller.handlerGetArticlesByGroup)
		apiGroup.Get("/articles/dictionary/:id", controller.handlerGetArticlesByDictionary)
		apiGroup.Post("/register", controller.handlerRegister)
		apiGroup.Post("/login", controller.handlerLogin)
	}

	restrictedApiGroup := apiGroup.Group("", jwtware.New(jwtware.Config{
		SigningKey: jwtware.SigningKey{Key: []byte(config.PrivateKey)},
	}))
	{
		restrictedApiGroup.Post("/article", controller.handlerCreateArticle)
		restrictedApiGroup.Post("/dictionary", controller.handlerCreateDictionary)
		restrictedApiGroup.Post("/group", controller.handlerCreateGroup)
		restrictedApiGroup.Post("/translations/:id", controller.handlerUpdateTranslations)
		restrictedApiGroup.Post("/group/articles/:id", controller.handlerAddGroupArticles)
		restrictedApiGroup.Delete("/translations/:id", controller.handlerDeleteTranslations)
		restrictedApiGroup.Delete("/article/:id", controller.handlerDeleteArticle)
		restrictedApiGroup.Delete("/group/:id", controller.handlerDeleteGroup)
		restrictedApiGroup.Delete("/dictionary/:id", controller.handlerDeleteDictionary)
		restrictedApiGroup.Delete("/group/articles/:id", controller.handlerDeleteGroupArticles)
	}
	return controller, nil
}

func (w *Controller) Run(ctx context.Context) error {
	go func() {
		<-ctx.Done()
		err := w.fiber.Shutdown()
		zap.L().Error("can't graceful shutdown fiber", zap.Error(err))
	}()

	err := w.fiber.Listen(w.config.WebAddr)
	if err != nil {
		return err
	}
	return nil
}
